name: 'Build Example corne nice_nano custom'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left","corne_right"]'
      kconfig: '["MIRYOKU_NAV=VI", "MIRYOKU_ALPHAS=QWERTY", "CONFIG_ZMK_DISPLAY=n"]'
