name: 'Build Example corne nice_nano custom'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left","corne_right"]'
      custom_config: '["#define MIRYOKU_NAV VI", "#define MIRYOKU_ALPHAS QWERTY"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=n"]'
