name: 'Build Example corne nice_nano custom'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left", "corne_right"]'
      nav: '["VI"]'
      alphas: '["QWERTY"]'
      kconfig: "[\"CONFIG_ZMK_DISPLAY=n\", \"CONFIG_ZMK_EXTENDED_ADV=n\", \"CONFIG_ZMK_BATTERY=y\", \"CONFIG_ZMK_BATTERY_REPORT=y\"]"
